name: Insider Monitor

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 7 * * *"   # dagelijks 07:15 UTC

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure config.local.yaml
        env:
          SEC_USER_AGENT: ${{ secrets.SEC_USER_AGENT }}
        run: |
          cp config.yaml config.local.yaml || true
          python - <<'PY'
          import os, yaml
          p='config.local.yaml'
          cfg={}
          if os.path.exists(p):
            cfg=yaml.safe_load(open(p)) or {}
          ua=os.getenv('SEC_USER_AGENT')
          if ua:
            cfg.setdefault('user_agent', {})['ua']=ua
          yaml.safe_dump(cfg, open(p,'w'), sort_keys=False, allow_unicode=True)
          print("✅ config.local.yaml geschreven")
          PY

      - name: Run pipeline
        run: |
          python scripts/fetch_insiders.py --days 1 --config config.local.yaml
          python scripts/score_signals.py   --config config.local.yaml
          python scripts/fetch_news.py      --config config.local.yaml
          python scripts/report_builder.py  --config config.local.yaml

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            data/reports/**
            data/*.csv
            data/*.json
