name: Insider Alerts (WhatsApp) — v2

on:
  workflow_dispatch:

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Twilio SDK
        run: |
          python -m pip install --upgrade pip
          pip install twilio

      # DEBUG: stuur ALTIJD een WhatsApp-bericht, zodat we kunnen testen/oefenen
      - name: Stuur WhatsApp (debug: altijd)
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN:  ${{ secrets.TWILIO_AUTH_TOKEN }}
          ALERT_TO_INSIDER:   ${{ secrets.ALERT_TO_INSIDER }}
        run: |
          python - <<'PY'
          from twilio.rest import Client
          import os

          sid = os.environ["TWILIO_ACCOUNT_SID"]
          tok = os.environ["TWILIO_AUTH_TOKEN"]
          to  = os.environ["ALERT_TO_INSIDER"]

          client = Client(sid, tok)

          body = "Insider Monitor testbericht (v2): dit is een DEBUG push met nieuws!"

          msg = client.messages.create(
              body=body,
              from_="whatsapp:+14155238886",   # Twilio sandbox nummer
              to=f"whatsapp:{to}"
          )
          print("WhatsApp verzonden! SID:", msg.sid)
          PY

      # (optioneel) upload de laatste samenvatting/rapporten als artifact — wordt genegeerd als er niets is
      - name: Upload rapporten (optioneel)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            data/reports/latest.txt
            data/reports/summary_*.txt
          if-no-files-found: ignore
