name: WhatsApp Ping (manual)

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install twilio
        run: python -m pip install --upgrade pip && pip install twilio

      - name: Send ping (logs masked; sanitize number)
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN:  ${{ secrets.TWILIO_AUTH_TOKEN }}
          ALERT_TO_INSIDER:   ${{ secrets.ALERT_TO_INSIDER }}
        run: |
          python - <<'PY'
          import os, re
          def sanitize_to(s):
              s=s.replace("\u00A0","").replace("\u202F","").replace("\u2007","").strip()
              s="".join(ch for ch in s if ch.isdigit() or ch=="+")
              if s.count("+")>1: s="+"+s.replace("+","")
              return s
          def mask(x): 
              return x if not x or len(x)<=5 else x[:3]+"…"+x[-2:]
          raw=os.getenv("ALERT_TO_INSIDER","")
          to=sanitize_to(raw)
          print("raw (masked):", mask(raw), "len:", len(raw), "cps:", [ord(c) for c in raw])
          print("sanitized (masked):", mask(to))
          from twilio.rest import Client
          sid=os.getenv("TWILIO_ACCOUNT_SID","").strip()
          tok=os.getenv("TWILIO_AUTH_TOKEN","").strip()
          if not re.fullmatch(r"\+\d{10,15}", to):
              raise SystemExit("ALERT_TO_INSIDER invalid after sanitize")
          msg=Client(sid,tok).messages.create(
              body="Insider Monitor – TEST: keten werkt ✅",
              from_="whatsapp:+14155238886",
              to=f"whatsapp:{to}",
          )
          print("Ping sent. SID:", msg.sid)
          PY
